package com.example.demo.serviceimpl;

import java.util.List;
import java.util.Objects;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.demo.model.User;
import com.example.demo.repository.UserRepository;
import com.example.demo.service.UserService;

@Service("userService")
public class UserServiceImpl implements UserService {

	@Autowired
	private UserRepository userRepository;


@Override	
    public boolean validateUser(String username, String password) {
        // Replace with DB validation
    	try {
    	userRepository.findByNameAndPassword(username, password).orElseThrow(() -> new RuntimeException("Invalid username or password"));
    	} catch (RuntimeException e) {
			return false;
		}
return true;
	}

	@Override
	public User addUser( User user) {		
		Objects.requireNonNull(user, "User must not be null");
   
		user.setId(null); // Ensure the ID is null so that it will be generated by the database
		// TODO Auto-generated method stub
		return 	userRepository.save(user);
	}



	@Override
	public String deleteUser(Integer id) {
	
if (id != null) {
		    User user = userRepository.findById(id)
		        .orElseThrow(() -> new RuntimeException("User not found"));

		    user.setIsDeleted(true);

		    userRepository.save(user);
}
		return "deleted successfully"+id;
	}

	@Override
	public List<User> fetchAllUser() {

		//Optional<List<User>> user = userRepository.findall().orElseThrow(() -> new ResourceNotFoundException("User not found"));

	    List<User> users = userRepository.findAll();

	    if (users.isEmpty()) {
	        throw new RuntimeException("No users found");
	    }

		return users;
		/*
		 * User u = user.orElseThrow( () -> new RuntimeException("User not found")
		 */
		
		//return userRepository.findAll();

	}

	
	
	@Override
	public User updateUser(Integer id, User user) {
		if (id != null) {
			Objects.requireNonNull(user, "User must not be null");
	    User existing = userRepository.findById(id)
	            .orElseThrow(() -> new RuntimeException("User not found"));
		
	    existing.setName(user.getName());
	    //existing.setEmail(user.g());
user=userRepository.save(existing);
		
	    return userRepository.save(existing);	
		}
		return null;

	}



}
